version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    ports:
      - "5432:5432"

  django:
    build:
      context: ./backend/django_project
      dockerfile: Dockerfile
    volumes:
      - ./backend/django_project:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings.dev
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  go_services:
    build:
      context: ./backend/go_services
      dockerfile: Dockerfile
    volumes:
      - ./backend/go_services:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - DJANGO_SERVICE_URL=http://django:8000
    depends_on:
      - django

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  postgres_data: 
